<?php

return [
    'title' => 'About',
    'subtitle' => 'The story behind the tool.',
    'paragraph_1' => 'As a French speaker learning Russian, I quickly ran into a practical problem: available Anki decks often lack correct stress marks, and it\'s hard to find quality audio resources to learn proper pronunciation.',
    'paragraph_2' => 'So I built this tool to meet my own needs: translate phrases, place stress marks with AI, generate high-quality synthesised audio for each card, and export everything as an .apkg file ready to import into Anki.',
    'paragraph_3' => 'If you\'re learning Russian too — whether you\'re a French speaker or not — I hope this tool proves as useful to you as it has been to me.',

    'how_title' => 'How does it work?',
    'how_intro' => 'All AI features on this site rely on the OpenAI API, called server-side for every operation. Nothing runs locally.',

    'how_translation_title' => 'Translation and stress correction',
    'how_translation_body' => 'A language model (GPT) translates your source phrases into natural Russian and automatically places stress marks on every multi-syllable word. A second pass can be triggered to correct stress marks on already-entered Russian text.',

    'how_tts_title' => 'Text-to-speech',
    'how_tts_body' => 'The OpenAI TTS API generates a high-quality MP3 audio file for each Russian phrase. Files are cached server-side: if a phrase has already been generated by any user, the existing audio is reused directly — no API call is made, saving tokens for everyone.',

    'how_export_title' => 'Anki export',
    'how_export_body' => 'Cards and their audio files are packaged into an .apkg file (Anki\'s native format) that you can import directly into the Anki app on any device.',

    'key_title' => 'Why do I need my own API key?',
    'key_paragraph_1' => 'This site does not hold a shared API key. Each user connects their own OpenAI key, which is used for all their requests. You consume and pay your own quota directly — no middleman.',
    'key_paragraph_2' => 'This is a deliberate choice: it gives you full control over your usage and costs. For typical personal use (a few dozen translations and audio files), the OpenAI bill amounts to just a few cents.',
    'key_paragraph_3' => 'Your key is stored encrypted in the database, is never exposed, and is only used for your own requests. You can add, change, or remove it at any time from your profile.',
];
