<?php

return [
    'title' => 'FAQ',
    'seo_description' => 'Frequently asked questions about Ankiru: AI reliability, stress mark correction, API key, costs, Anki export, and more.',
    'subtitle' => 'The most common questions, answered honestly.',

    // Section AI & Quality
    'section_ai_title' => 'AI & quality',

    'q_ai_reliable' => 'Are AI-generated phrases reliable?',
    'a_ai_reliable' => 'The AI generally produces natural, correct phrases, but it\'s not perfect. GPT can occasionally generate awkward phrasing or slight inaccuracies, especially on specialised topics. Treat the results as an excellent starting point and review them before committing to your final cards.',

    'q_stress_unreliable' => 'The automatic stress mark correction doesn\'t always work. Why?',
    'a_stress_unreliable' => 'Russian stress marks (ударения) are notoriously complex: their position can shift depending on the grammatical case, verb form, or register. Even native Russian speakers make mistakes sometimes. The GPT model does its best, but can get it wrong on rare words, atypical verb forms, or homographs. If a stress mark seems off, you can always fix it manually by editing the cell directly.',

    'q_translation_quality' => 'How good are the translations?',
    'a_translation_quality' => 'For everyday phrases, quality is generally very good. GPT understands context and produces natural Russian. Limitations appear mainly with highly idiomatic expressions, technical jargon, or wordplay. A quick review is still recommended.',

    'q_tts_quality' => 'Is the generated audio good quality?',
    'a_tts_quality' => 'Yes. OpenAI\'s TTS API produces a very natural result with careful Russian pronunciation. To save your credits, audio files are cached server-side: if the exact same phrase has already been generated by another user, you get the file instantly at no cost to you.',

    // Section API Key & Costs
    'section_api_title' => 'API key & costs',

    'q_why_own_key' => 'Why do I need my own OpenAI API key?',
    'a_why_own_key' => 'The app is free, but OpenAI API calls cost money. Rather than charging a subscription or selling marked-up credits, I chose to let you plug in your own key. You pay OpenAI directly for exactly what you use, with no middleman.',

    'q_cost_estimate' => 'How much does it actually cost?',
    'a_cost_estimate' => 'For typical personal use (a few dozen phrases and audio files), expect a few cents. Text generation and stress mark corrections are very cheap with the latest models. TTS is slightly more expensive per character, but still very affordable. A cost estimate is shown before every bulk operation.',

    'q_key_security' => 'Is my API key secure?',
    'a_key_security' => 'Your key is encrypted in the database and is never exposed in the frontend or in application logs. You can update or delete it at any time from your profile.',

    // Section How it works
    'section_usage_title' => 'How it works',

    'q_offline' => 'Can I use the app without an internet connection?',
    'a_offline' => 'Partially. Browsing your phrases and listening to already-generated audio files works locally. However, all AI features (generation, translation, stress correction, and TTS) require a call to the OpenAI API and therefore need an active connection.',

    'q_other_languages' => 'Does the app support languages other than Russian?',
    'a_other_languages' => 'For now, the app is specifically designed for learning Russian. The stress mark correction feature is unique to Russian, and the AI prompts are calibrated for this language. Support for other languages is not planned in the near term.',

    'q_data_privacy' => 'Is my data shared with third parties?',
    'a_data_privacy' => 'Your phrases are sent to the OpenAI API for processing: that\'s inherent to how the tool works. No personal data is sold or shared for commercial purposes. See our privacy policy for full details.',

    // Section Export
    'section_export_title' => 'Anki export',

    'q_how_export_works' => 'How does the Anki export work?',
    'a_how_export_works' => 'Your phrases and audio files are packaged into a standard .apkg file. Open that file from the Anki application (or just double-click it) to import all cards into a deck. The file contains both the front/back fields and the linked audio files.',

    'q_export_all_at_once' => 'Can I export all my files at once?',
    'a_export_all_at_once' => 'Yes. Use the "Export collection" option in the export menu. It bundles all your decks into a single .apkg file, handy for a clean Anki reinstall or for sharing your collection.',

    'q_missing_audio_in_anki' => 'Some cards are missing audio in Anki. What should I do?',
    'a_missing_audio_in_anki' => 'First check that the audio has been generated for those rows in the editor (the audio icon appears greyed out when audio is missing). Once the audio is generated, re-export the .apkg package and re-import it in Anki.',
];
